import Foundation
import CryptoKit

/// Offline, cryptographically-signed licensing — so you can hand the signed DMG plus a license key
/// to friends and they get unlimited local use, with **no server and no network**.
///
/// How it works: you hold an Ed25519 **private** key (kept on your machine, never in the app or
/// repo); the app embeds the matching **public** key. `demotape --gen-license "Name"` signs a tiny
/// payload; the app verifies that signature against the embedded public key. A license can't be
/// forged without your private key, and verification is fully local. (Offline licenses are
/// intentionally shareable — that's the point here: gift them to friends.)
///
/// License string format:  base64(payloadJSON) + "." + base64(signature)
enum License {

    /// Embedded Ed25519 PUBLIC key (32-byte raw, base64) for Kiff Agents / DemoTape. Generated by
    /// `demotape --license-keygen`; the matching private key stays on the issuer's machine only.
    static let publicKeyBase64 = "iXgMeBmvJ8cf9dw+OYrErdUfDeZpOA2pzJbRvWR1R+Y="

    /// What a license grants. `kind` lets us add tiers later without breaking old keys.
    struct Info: Codable, Equatable {
        var name: String
        var issued: Date
        var kind: String
        var id: String
    }

    // MARK: - Verification (pure / testable)

    /// Verifies a license string against a public key and returns its info, or nil if invalid.
    static func verify(_ license: String, publicKeyBase64 key: String = publicKeyBase64) -> Info? {
        guard !key.isEmpty,
              let keyData = Data(base64Encoded: key),
              let publicKey = try? Curve25519.Signing.PublicKey(rawRepresentation: keyData)
        else { return nil }

        let parts = license.trimmingCharacters(in: .whitespacesAndNewlines).split(separator: ".")
        guard parts.count == 2,
              let payload = Data(base64Encoded: String(parts[0])),
              let signature = Data(base64Encoded: String(parts[1])),
              publicKey.isValidSignature(signature, for: payload)
        else { return nil }

        return try? JSONDecoder.licenseDecoder.decode(Info.self, from: payload)
    }

    /// Builds the exact signable payload bytes for a license (shared by signer + tests).
    static func payload(name: String, issued: Date, kind: String = "desktop-unlimited",
                        id: String = UUID().uuidString) throws -> (data: Data, info: Info) {
        let info = Info(name: name, issued: issued, kind: kind, id: id)
        return (try JSONEncoder.licenseEncoder.encode(info), info)
    }

    /// Assembles the shareable license string from a payload + signature.
    static func assemble(payload: Data, signature: Data) -> String {
        payload.base64EncodedString() + "." + signature.base64EncodedString()
    }

    // MARK: - Stored license (Keychain)

    /// The currently-activated license, if a valid one is stored.
    static func current() -> Info? {
        guard let stored = Keychain.get(account: Keychain.licenseAccount) else { return nil }
        return verify(stored)
    }

    /// True when a valid license is stored. The single checkpoint the rest of the app reads.
    static var isActivated: Bool { current() != nil }

    /// Validates and stores a pasted license. Returns the info on success, nil if it doesn't verify.
    @discardableResult
    static func activate(_ license: String) -> Info? {
        let trimmed = license.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let info = verify(trimmed) else { return nil }
        _ = Keychain.set(trimmed, account: Keychain.licenseAccount)
        return info
    }

    static func deactivate() { Keychain.remove(account: Keychain.licenseAccount) }
}

extension JSONEncoder {
    /// Deterministic encoder so the signed bytes are stable (sorted keys, epoch dates).
    static var licenseEncoder: JSONEncoder {
        let e = JSONEncoder()
        e.outputFormatting = [.sortedKeys]
        e.dateEncodingStrategy = .secondsSince1970
        return e
    }
}
extension JSONDecoder {
    static var licenseDecoder: JSONDecoder {
        let d = JSONDecoder()
        d.dateDecodingStrategy = .secondsSince1970
        return d
    }
}
